<?php

namespace App\Collections;

use Illuminate\Database\Eloquent\Collection;

class BaseEloquentCollection extends Collection
{


    public function pluck($value, $key = null)
    {
        return parent::pluck($value, $key)->first(); // TODO: Change the autogenerated stub
    }
}