<?php

namespace Tests\Unit;

use Tests\TestCase;
use App\Models\Disorder;
use Illuminate\Foundation\Testing\RefreshDatabase;

class DisorderRulesTest extends TestCase
{
    use RefreshDatabase;

    public function testDisorderHavingRules()
    {
        $disorder  = Disorder::whereName('Swapped Electrodes')->first();
        $rules     = $disorder->rules;
        $criterias = $rules->pluck('criterion');
        $rule      = $disorder->rules()
                              ->whereRule('exclude_if:p_available,true|in:negative')
                              ->whereHas('criterion', function ($q) {
                                  $q->where('name', 'I_p_dir');
                              })
                              ->first();
        $this->assertEquals('exclude_if:p_available,true|in:negative', $rule->rule);
        $this->assertEquals('I_p_dir', $rule->criterion->name);
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
    }

    use RefreshDatabase;
}